DacDac
site_name: 'Giveth Wiki'
site_url: https://wiki.giveth.io
site_author: 'The Giveth DAC'
site_description: 'Learn about Giveth'
repo_name: '/giveth-wiki'
repo_url: https://github.com/Giveth/giveth-wiki/
edit_uri: edit/master/wiki/
docs_dir: wiki

theme:
  name: 'material'
  custom_dir: 'material'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  language: 'en'

google_analytics: ['UA-103956937-1', 'giveth.io']

extra:
    palette:
      primary: 'deep purple'
      accent: 'green'
    social:
    - type: 'comment-o'
      link: 'http://join.giveth.io/'
    - type: 'medium'
      link: 'https://medium.com/giveth'
    - type: 'twitter'
      link: 'https://twitter.com/givethio'
    - type: 'github'
      link: 'https://github.com/giveth'
    - type: 'facebook'
      link: 'https://facebook.com/givethio'
    - type: 'youtube'
      link: 'https://www.youtube.com/watch?v=VaIbmxk2eio&list=PL4Artm1rmCWGyz-BWv1-8Ip26XIauCLo9'

extra_css:
    - css/extra.css

nav:
    - Welcome: 'index.md'
    - General:
        - Our Mission: 'Dac/mission.md'
        - Calendar and Events: 'Dac/calendar.md'
    - Dapp Development:
      - Intro to the Giveth DApp: 'DApp/index.md'
      - Product Definition: 'DApp/product-definition.md'
      - Roadmap: 'DApp/product-roadmap.md'
      - Documentation and Tutorials:
        - How to make Milestones: 'DApp/milestones.md'
        - Future: 'DApp/future.md'
        - Exchange Rate: 'DApp/exchange-rate-calculation.md'
        - Dev Process & QA: 'DApp/product-development-testing.md'
        - Smart Contracts Roadmap: 'DApp/smart-contracts-roadmap.md'
        - Deployments: 'DApp/deployments.md'
    - Social Coding:
      - Intro to Giveth Social Coding: 'social-coding/index.md'
      #- The Blockternship: 'social-coding/blockternship.md'
      #- Stars and Planets: 'social-coding/stars-and-planets.md'
    - Governance:
      - Intro to Giveth Governance: 'Governance/index.md'
      - Governance model: 'Governance/governance.md'
      - Tools for DACs: 'Governance/tools-for-dacs.md'
      - Governance Experiments:
        - Unicorn DAC:
          - Unicorn DAC Intro: 'Governance/Unicorn-DAC/index.md'
          - Unicorn Onboarding: 'Governance/Unicorn-DAC/unicorn-onboarding.md'
          - Get Funding: 'Governance/Unicorn-DAC/unicorn-dac-getfunded.md'
          - Roles Process: 'Governance/Unicorn-DAC/roles.md'
      - Documentation and Tutorials:
        - Milestone Tutorial: 'Governance/milestones.md'
        - Code of Conduct: 'Governance/codeofconduct.md'
        - Conflict Resolution: 'Governance/conflict-res.md'
        - Governance of Meetings: 'Governance/meeting-notes/governance-meetings.md'
        - Advice Process: 'Governance/advice-process.md'
    - Communication:
       - Intro to Giveth Communications: 'Communications/index.md'
       - Documentation and Tutorials:
          - Brand Identity Guide: 'Communications/brand-guidelines.md'
          - Use of Riot Chat: 'Communications/riot-migration.md'
    - Giveth Community (DAC):
        - Welcome to the Giveth DAC: 'Dac/index.md'
        - Team Organisation: 'Dac/team-organisation.md'
        - Finances: 'Dac/finances.md'
        - History: 'Dac/history.md'
        - Documentation and Tutorials:
          - Contributors Guide: 'Dac/contributors-guide.md'
          - Adopted Policies: 'Dac/approved-policies.md'
          - Meeting Notes:
            - About our DAC Meetings: 'Dac/meeting-notes/intro-recap.md'
            - Governance Meeting 01: 'Dac/meeting-notes/gov-meeting-1.md'
            - Governance Meeting 02: 'Dac/meeting-notes/gov-meeting-2.md'
            - Governance Meeting 03: 'Dac/meeting-notes/gov-meeting-3.md'
            - Governance Meeting 04: 'Dac/meeting-notes/gov-meeting-4.md'
            - Governance Meeting 05: 'Dac/meeting-notes/gov-meeting-5.md'
            - Governance Meeting 06: 'Dac/meeting-notes/gov-meeting-6.md'
            - Governance Meeting 07: 'Dac/meeting-notes/gov-meeting-7.md'
            - Governance Meeting 08: 'Dac/meeting-notes/gov-meeting-8.md'
            - Governance Meeting 09: 'Dac/meeting-notes/gov-meeting-9.md'
            - Governance Meeting 10: 'Dac/meeting-notes/gov-meeting-10.md'
            - Governance Meeting 11: 'Dac/meeting-notes/gov-meeting-11.md'
            - Governance Meeting 12: 'Dac/meeting-notes/gov-meeting-12.md'
            - Governance Meeting 13: 'Dac/meeting-notes/gov-meeting-13.md'
            - Governance Meeting 14: 'Dac/meeting-notes/gov-meeting-14.md'
            - Governance Meeting 15: 'Dac/meeting-notes/gov-meeting-15.md'
            - Governance Meeting 16: 'Dac/meeting-notes/gov-meeting-16.md'
            - Governance Meeting 17: 'Dac/meeting-notes/gov-meeting-17.md'
            - Governance Meeting 18: 'Dac/meeting-notes/gov-meeting-18.md'
            - Governance Meeting 19: 'Dac/meeting-notes/gov-meeting-19.md'
            - Governance Meeting 20: 'Dac/meeting-notes/gov-meeting-20.md'
            - Governance Meeting 21: 'Dac/meeting-notes/gov-meeting-21.md'
            - Governance Meeting 25: 'Dac/meeting-notes/gov-meeting-25.md'
            - Governance Meeting 26: 'Dac/meeting-notes/gov-meeting-26.md'
            - Governance Meeting 27: 'Dac/meeting-notes/gov-meeting-27.md'
            - Governance Meeting 28: 'Dac/meeting-notes/gov-meeting-28.md'
            - Governance Meeting 30: 'Dac/meeting-notes/gov-meeting-30.md'
            - Governance Meeting 31: 'Dac/meeting-notes/gov-meeting-31.md'
            - Governance Meeting 32: 'Dac/meeting-notes/gov-meeting-32.md'
            - Governance Meeting 33: 'Dac/meeting-notes/gov-meeting-33.md'
            - Onboarding Meeting: 'Dac/meeting-notes/onboarding-meeting.md'
            - Governance Meeting 34: 'Dac/meeting-notes/gov-meeting-34.md'
            - Governance Meeting 35: 'Dac/meeting-notes/gov-meeting-35.md'
            - Transparency Meeting: 'Dac/meeting-notes/transparency-meeting.md'
            - Governance Meeting 36: 'Dac/meeting-notes/gov-meeting-36.md'
            - Governance Meeting 37: 'Dac/meeting-notes/gov-meeting-37.md'
            - Governance Meeting 38: 'Dac/meeting-notes/gov-meeting-38.md'
            - Governance Meeting 39: 'Dac/meeting-notes/gov-meeting-39.md'
            - Governance Meeting 40: 'Dac/meeting-notes/gov-meeting-40.md'
            - Governance Meeting 41: 'Dac/meeting-notes/gov-meeting-41.md'
            - Governance Meeting 42: 'Dac/meeting-notes/gov-meeting-42.md'
            - Roles Meeting 1: 'Dac/meeting-notes/roles-meeting-1.md'
            - Governance Meeting 43: 'Dac/meeting-notes/gov-meeting-43.md'
            - Governance Meeting 44: 'Dac/meeting-notes/gov-meeting-44.md'
            - Governance Meeting 45: 'Dac/meeting-notes/gov-meeting-45.md'
            - Governance Meeting 47: 'Dac/meeting-notes/gov-meeting-47.md'
            - Governance Meeting 48: 'Dac/meeting-notes/gov-meeting-48.md'
            - Governance Meeting 49: 'Dac/meeting-notes/gov-meeting-49.md'
            - Governance Meeting 50: 'Dac/meeting-notes/gov-meeting-50.md'
