site_name: 'Giveth Wiki'
site_url: https://wiki.giveth.io
site_author: 'The Giveth DAC'
site_description: 'Learn about Giveth'
repo_name: '/giveth-wiki'
repo_url: https://github.com/Giveth/giveth-wiki/
edit_uri: edit/master/wiki/
docs_dir: wiki

theme:
  name: 'material'
  custom_dir: 'material'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  language: 'en'

google_analytics: ['UA-103956937-1', 'giveth.io']

extra:
    palette:
      primary: 'deep purple'
      accent: 'green'
    social:
    - type: 'comment-o'
      link: 'http://join.giveth.io/'
    - type: 'medium'
      link: 'https://medium.com/giveth'
    - type: 'twitter'
      link: 'https://twitter.com/givethio'
    - type: 'github'
      link: 'https://github.com/giveth'
    - type: 'facebook'
      link: 'https://facebook.com/givethio'
    - type: 'youtube'
      link: 'https://www.youtube.com/watch?v=VaIbmxk2eio&list=PL4Artm1rmCWGyz-BWv1-8Ip26XIauCLo9'

extra_css:
    - css/extra.css

nav:
    - Welcome: 'index.md'
    - General:
        - Our Mission: 'dac/mission.md'
        - Calendar and Events: 'dac/calendar.md'
    - Dapp Development: 
      - DApp Beta: 'DApp/beta.md'
      - Product Definition: 'DApp/product-definition.md'
      - Roadmap: 'DApp/product-roadmap.md'
      - Documentation: 
        - Future: 'DApp/future.md'
        - Exchange Rate: 'DApp/exchange-rate-calculation.md'
        - Dev Process & QA: 'DApp/product-development-testing.md'
        - Smart Contracts Roadmap: 'DApp/smart-contracts-roadmap.md'
        - Deployments: 'DApp/deployments.md'
    - Social Coding: 
      - What is Social Coding?: 'social-coding/what-is-social-coding.md'
      #- The Blockternship: 'social-coding/blockternship.md'
      #- Stars and Planets: 'social-coding/stars-and-planets.md'
    - Governance:
      - Governance model: 'dac/governance.md'
      - Team Organisation: 'dac/team-organisation.md'
      - Contributors Guide: 'dac/contributors-guide.md'
      - Milestones: 'tutorials/milestones.md'
      - Unicorn DAC: 'dac/unicorn-dac.md'
      - Unicorn Onboarding: 'dac/unicorn-onboarding.md'
      - Unicorn DAC Get Funding: 'dac/unicorn-dac-getfunded.md'
      - Policy and Research:
        #- Intro Page: 'policy/policy-introduction.md'
        - Code of Conduct: 'policy/codeofconduct.md'
        - Adopted Policies: 'policy/approved-policies.md'
        - Roles Process: 'policy/roles.md'
        - Conflict Resolution: 'policy/conflict-res.md'
        - Governance Meetings: 'meeting-notes/governance-meetings.md'
        - Advice Process: 'policy/advice-process.md'
    - Communication: 
       - Goals for Comms: 'communications/communications.md'
       - Brand Identity Guide: 'communications/brand-guidelines.md'
    - Giveth Community (DAC):
        - About the Team: 'dac/about-team.md' 
        - Tools for DACs: 'dac/tools-for-dacs.md'
        - Finances: 'dac/finances.md'
        - History: 'dac/history.md'        
        - Meeting Notes:
            - About these pages: 'meeting-notes/about-meeting-notes.md'
            - Governance Meeting 01: 'meeting-notes/gov-meeting-1.md'
            - Governance Meeting 02: 'meeting-notes/gov-meeting-2.md'
            - Governance Meeting 03: 'meeting-notes/gov-meeting-3.md'
            - Governance Meeting 04: 'meeting-notes/gov-meeting-4.md'
            - Governance Meeting 05: 'meeting-notes/gov-meeting-5.md'
            - Governance Meeting 06: 'meeting-notes/gov-meeting-6.md'
            - Governance Meeting 07: 'meeting-notes/gov-meeting-7.md'
            - Governance Meeting 08: 'meeting-notes/gov-meeting-8.md'
            - Governance Meeting 09: 'meeting-notes/gov-meeting-9.md'
            - Governance Meeting 10: 'meeting-notes/gov-meeting-10.md'
            - Governance Meeting 11: 'meeting-notes/gov-meeting-11.md'
            - Governance Meeting 12: 'meeting-notes/gov-meeting-12.md'
            - Governance Meeting 13: 'meeting-notes/gov-meeting-13.md'
            - Governance Meeting 14: 'meeting-notes/gov-meeting-14.md'
            - Governance Meeting 15: 'meeting-notes/gov-meeting-15.md'
            - Governance Meeting 16: 'meeting-notes/gov-meeting-16.md'
            - Governance Meeting 17: 'meeting-notes/gov-meeting-17.md'
            - Governance Meeting 18: 'meeting-notes/gov-meeting-18.md'
            - Governance Meeting 19: 'meeting-notes/gov-meeting-19.md'
            - Governance Meeting 20: 'meeting-notes/gov-meeting-20.md'
            - Governance Meeting 21: 'meeting-notes/gov-meeting-21.md'
            - Governance Meeting 25: 'meeting-notes/gov-meeting-25.md'
            - Governance Meeting 26: 'meeting-notes/gov-meeting-26.md'
            - Governance Meeting 27: 'meeting-notes/gov-meeting-27.md'
            - Governance Meeting 28: 'meeting-notes/gov-meeting-28.md'
            - Governance Meeting 30: 'meeting-notes/gov-meeting-30.md'
            - Governance Meeting 31: 'meeting-notes/gov-meeting-31.md'
            - Governance Meeting 32: 'meeting-notes/gov-meeting-32.md'
            - Governance Meeting 33: 'meeting-notes/gov-meeting-33.md'
            - Onboarding Meeting: 'meeting-notes/onboarding-meeting.md'
            - Governance Meeting 34: 'meeting-notes/gov-meeting-34.md'
            - Governance Meeting 35: 'meeting-notes/gov-meeting-35.md'
            - Transparency Meeting: 'meeting-notes/transparency-meeting.md'
            - Governance Meeting 36: 'meeting-notes/gov-meeting-36.md'
            - Governance Meeting 37: 'meeting-notes/gov-meeting-37.md'
            - Governance Meeting 38: 'meeting-notes/gov-meeting-38.md'
            - Governance Meeting 39: 'meeting-notes/gov-meeting-39.md'
            - Governance Meeting 40: 'meeting-notes/gov-meeting-40.md'
            - Governance Meeting 41: 'meeting-notes/gov-meeting-41.md'
            - Governance Meeting 42: 'meeting-notes/gov-meeting-42.md'
            - Roles Meeting 1: 'meeting-notes/roles-meeting-1.md'
            - Governance Meeting 43: 'meeting-notes/gov-meeting-43.md'
            - Governance Meeting 44: 'meeting-notes/gov-meeting-44.md'
            - Governance Meeting 45: 'meeting-notes/gov-meeting-45.md'
            - Governance Meeting 47: 'meeting-notes/gov-meeting-47.md'
            - Governance Meeting 48: 'meeting-notes/gov-meeting-48.md'
            - Governance Meeting 49: 'meeting-notes/gov-meeting-49.md'
            - Governance Meeting 50: 'meeting-notes/gov-meeting-50.md'
    

